name: returnit
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.2.1
  cloud_firestore: ^6.1.0
  firebase_auth: ^6.1.2
  email_otp: ^2.1.0
  crypto: ^3.0.3
  google_fonts: ^6.1.0
  intl: ^0.19.0
  uuid: 4.5.2
  shared_preferences: ^2.5.3
  firebase_storage: 13.0.4
  image_picker: ^1.1.2
  http: ^1.6.0
  timeago: ^3.7.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
